# .github/workflows/eas-build.yml
name: EAS Build (Android)

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1) 전체 히스토리 가져오기
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Node.js 세팅
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Corepack 활성화 & Yarn 버전 고정
      - run: |
          corepack enable
          yarn set version stable

      # 4) 프로젝트 의존성 설치
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5) Expo 로그인
      - name: Login to Expo
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: |
          eas whoami || eas login --token "$EAS_ACCESS_TOKEN"

      # 6) Android Development Build
      - name: Run Android development build
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: |
          eas build --platform android \
                    --profile development \
                    --non-interactive