name: EAS Build (Android)

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # 1) 전체 히스토리 + 서브모듈 무시
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      # 2) Node.js 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 의존성 설치 (Yarn v4 권장 플래그)
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      # 4) Expo 로그인
      - name: Login to Expo
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: |
          yarn eas whoami || yarn eas login --token "$EAS_ACCESS_TOKEN"

      # 5) Android 개발용 빌드
      - name: Run Android development build
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: yarn eas build --platform android --profile development --non-interactive