name: EAS Build (Android)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run Android EAS build (development)
        run: |
          echo "→ building with profile: development"
          npx eas build \
            --platform android \
            --profile development \
            --non-interactive