name: EAS Build (Android)

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run Android development build
        env:
          # 여기에 EXPO_TOKEN 또는 EAS_ACCESS_TOKEN 중 하나만 있어도 됩니다
          EXPO_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: npx eas build --platform android --profile development --non-interactive