name: EAS Build (Android — Production)

on:
  push:
    branches: [main]

# Optional: 같은 워크플로우가 겹치지 않도록 처리
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run Android production build
        env:
          # EXPO_TOKEN or EAS_ACCESS_TOKEN 중 하나만 설정
          EXPO_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}
        run: npx eas build --platform android --profile production --non-interactive