name: EAS Build (Android)

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0          # 전체 히스토리 clone
          submodules: 'false'   # ← 서브모듈 무시

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Install dependencies
        run: npm ci               # lockfile 사용

      - name: Login to Expo
        run: eas whoami || eas login --token "$EAS_ACCESS_TOKEN"
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}

      - name: Trigger Android dev build
        run: eas build --platform android --profile development --non-interactive
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}